# Website
home:
    pattern:  /
    defaults: { _controller: MilleEtangsRandonneesBundle:Default:index }

render_image:
    pattern: /images/{id}
    defaults: { _controller: MilleEtangsRandonneesBundle:Default:renderImage}

mille_etangs:    
    pattern:  /les-mille-etangs
    defaults: { _controller: MilleEtangsRandonneesBundle:Default:milleEtangs }

events:    
    pattern:  /evenements
    defaults: { _controller: MilleEtangsRandonneesBundle:Default:events }

articles:    
    pattern:  /articles
    defaults: { _controller: MilleEtangsRandonneesBundle:Articles:articles }

accomodations:    
    pattern:  /hebergement
    defaults: { _controller: MilleEtangsRandonneesBundle:Default:accomodations }

restaurants:    
    pattern:  /restauration
    defaults: { _controller: MilleEtangsRandonneesBundle:Default:restaurants }

partners:    
    pattern:  /partenaires
    defaults: { _controller: MilleEtangsRandonneesBundle:Default:partners }

advice:    
    pattern:  /conseils
    defaults: { _controller: MilleEtangsRandonneesBundle:Default:advice }

legal:
    pattern:  /mentions-legales
    defaults: { _controller: MilleEtangsRandonneesBundle:Default:legal }

contact:    
    pattern:  /contact
    defaults: { _controller: MilleEtangsRandonneesBundle:Default:contact }

sitemap:    
    pattern:  /sitemap
    defaults: { _controller: MilleEtangsRandonneesBundle:Sitemap:sitemap }

sitemap_xml:    
    pattern:  /sitemap.{_format}
    defaults: { _controller: MilleEtangsRandonneesBundle:Sitemap:sitemap }
    requirements:
      _format:  html|xml

rss:    
    pattern:  /rss.xml
    defaults: { _controller: MilleEtangsRandonneesBundle:Articles:rss }

render_kml:
    pattern: /kml/{id}.kml
    defaults: { _controller: MilleEtangsRandonneesBundle:Itinearies:renderKml}

download_gpx:
    pattern: /gpx/{id}.gpx
    defaults: { _controller: MilleEtangsRandonneesBundle:Itinearies:downloadGpx}

itinearies:
    pattern:  /randonnees
    defaults: { _controller: MilleEtangsRandonneesBundle:Itinearies:itinearies }

itinearies_type:
    pattern:  /randonnees/{type}
    defaults: { _controller: MilleEtangsRandonneesBundle:Itinearies:itinearies }

itineary:    
    pattern:  /randonnee/{slug}
    defaults: { _controller: MilleEtangsRandonneesBundle:Itinearies:itineary }