# Security
login:
    pattern: /secured/login
    defaults: { _controller: MilleEtangsRandonneesBundle:Security:login }

login_check:
    pattern: /secured/login_check
    defaults: { _controller: MilleEtangsRandonneesBundle:Security:loginCheck }

logout:
    pattern: /secured/logout
    defaults: { _controller: MilleEtangsRandonneesBundle:Security:logout }

admin_menu:
    pattern: /secured/menu
    defaults: { _controller: MilleEtangsRandonneesBundle:Security:menu }

create_randonnee:
    pattern: /secured/randonnees/create
    defaults: { _controller: MilleEtangsRandonneesBundle:Security:createRandonnee }

# Website
home:
    pattern:  /
    defaults: { _controller: MilleEtangsRandonneesBundle:Default:index }

randonnees_type:    
    pattern:  /randonnees/{type}
    defaults: { _controller: MilleEtangsRandonneesBundle:Default:randonnees }

randonnees:    
    pattern:  /randonnees
    defaults: { _controller: MilleEtangsRandonneesBundle:Default:randonnees }

randonnee:    
    pattern:  /randonnees/{type}/{slug}
    defaults: { _controller: MilleEtangsRandonneesBundle:Default:randonnee }

milleEtangs:    
    pattern:  /les-mille-etangs
    defaults: { _controller: MilleEtangsRandonneesBundle:Default:milleEtangs }

evenements:    
    pattern:  /evenements
    defaults: { _controller: MilleEtangsRandonneesBundle:Default:evenements }

hebergement:    
    pattern:  /hebergement
    defaults: { _controller: MilleEtangsRandonneesBundle:Default:hebergement }

restauration:    
    pattern:  /restauration
    defaults: { _controller: MilleEtangsRandonneesBundle:Default:restauration }

partenaires:    
    pattern:  /partenaires
    defaults: { _controller: MilleEtangsRandonneesBundle:Default:partenaires }

contact:    
    pattern:  /contact
    defaults: { _controller: MilleEtangsRandonneesBundle:Default:contact }

sitemap:    
    pattern:  /sitemap
    defaults: { _controller: MilleEtangsRandonneesBundle:Default:sitemap }