# Security
login:
    pattern: /secured/login
    defaults: { _controller: MilleEtangsRandonneesBundle:Security:login }

login_check:
    pattern: /secured/login_check
    defaults: { _controller: MilleEtangsRandonneesBundle:Security:loginCheck }

logout:
    pattern: /secured/logout
    defaults: { _controller: MilleEtangsRandonneesBundle:Security:logout }

admin_menu:
    pattern: /secured/menu
    defaults: { _controller: MilleEtangsRandonneesBundle:Security:menu }

create_randonnee:
    pattern: /secured/randonnees/create
    defaults: { _controller: MilleEtangsRandonneesBundle:Security:createRandonnee }

update_randonnee:
    pattern: /secured/randonnees/update/{id}
    defaults: { _controller: MilleEtangsRandonneesBundle:Security:updateRandonnee }

create_actualite:
    pattern: /secured/actualites/create
    defaults: { _controller: MilleEtangsRandonneesBundle:Security:createActualite }

update_actualite:
    pattern: /secured/actualites/update/{id}
    defaults: { _controller: MilleEtangsRandonneesBundle:Security:updateActualite }

upload_picture:
    pattern: /secured/upload_picture
    defaults: { _controller: MilleEtangsRandonneesBundle:Security:uploadPicture}

# Website
home:
    pattern:  /
    defaults: { _controller: MilleEtangsRandonneesBundle:Default:index }

randonnees_type:    
    pattern:  /randonnees/{type}
    defaults: { _controller: MilleEtangsRandonneesBundle:Default:randonnees }

#randonnees:    
#    pattern:  /randonnees
#    defaults: { _controller: MilleEtangsRandonneesBundle:Default:randonnees }

randonnee:    
    pattern:  /randonnee/{slug}
    defaults: { _controller: MilleEtangsRandonneesBundle:Default:randonnee }

milleEtangs:    
    pattern:  /les-mille-etangs
    defaults: { _controller: MilleEtangsRandonneesBundle:Default:milleEtangs }

evenements:    
    pattern:  /evenements
    defaults: { _controller: MilleEtangsRandonneesBundle:Default:evenements }

actualites:    
    pattern:  /actualites
    defaults: { _controller: MilleEtangsRandonneesBundle:Default:actualites }

hebergement:    
    pattern:  /hebergement
    defaults: { _controller: MilleEtangsRandonneesBundle:Default:hebergement }

restauration:    
    pattern:  /restauration
    defaults: { _controller: MilleEtangsRandonneesBundle:Default:restauration }

partenaires:    
    pattern:  /partenaires
    defaults: { _controller: MilleEtangsRandonneesBundle:Default:partenaires }

conseils:    
    pattern:  /conseils
    defaults: { _controller: MilleEtangsRandonneesBundle:Default:conseils }

contact:    
    pattern:  /contact
    defaults: { _controller: MilleEtangsRandonneesBundle:Default:contact }

sitemap:    
    pattern:  /sitemap
    defaults: { _controller: MilleEtangsRandonneesBundle:Default:sitemap }

sitemap_xml:    
    pattern:  /sitemap.{_format}
    defaults: { _controller: MilleEtangsRandonneesBundle:Default:sitemap }
    requirements:
      _format:  html|xml

rss:    
    pattern:  /rss.xml
    defaults: { _controller: MilleEtangsRandonneesBundle:Default:rss }