# Security
login:
    pattern: /secured/login
    defaults: { _controller: MilleEtangsRandonneesBundle:Security:login }

login_check:
    pattern: /secured/login_check
    defaults: { _controller: MilleEtangsRandonneesBundle:Security:loginCheck }

logout:
    pattern: /secured/logout
    defaults: { _controller: MilleEtangsRandonneesBundle:Security:logout }

admin_menu:
    pattern: /secured/menu
    defaults: { _controller: MilleEtangsRandonneesBundle:Security:menu }

create_itineary:
    pattern: /secured/itineary/create
    defaults: { _controller: MilleEtangsRandonneesBundle:Security:createItineary }

update_itineary:
    pattern: /secured/itineary/update/{id}
    defaults: { _controller: MilleEtangsRandonneesBundle:Security:updateItineary }

create_article:
    pattern: /secured/articles/create
    defaults: { _controller: MilleEtangsRandonneesBundle:Security:createArticle }

update_article:
    pattern: /secured/articles/update/{id}
    defaults: { _controller: MilleEtangsRandonneesBundle:Security:updateArticle }

upload_image:
    pattern: /secured/upload_image
    defaults: { _controller: MilleEtangsRandonneesBundle:Security:uploadImage}

# Website
home:
    pattern:  /
    defaults: { _controller: MilleEtangsRandonneesBundle:Default:index }

render_image:
    pattern: /images/{id}
    defaults: { _controller: MilleEtangsRandonneesBundle:Default:renderImage}

download_gpx:
    pattern: /gpx/{id}
    defaults: { _controller: MilleEtangsRandonneesBundle:Default:downloadGpx}

itinearies:
    pattern:  /randonnees
    defaults: { _controller: MilleEtangsRandonneesBundle:Default:itinearies }

itinearies_type:
    pattern:  /randonnees/{type}
    defaults: { _controller: MilleEtangsRandonneesBundle:Default:itinearies }

itineary:    
    pattern:  /randonnee/{slug}
    defaults: { _controller: MilleEtangsRandonneesBundle:Default:itineary }

milleEtangs:    
    pattern:  /les-mille-etangs
    defaults: { _controller: MilleEtangsRandonneesBundle:Default:milleEtangs }

events:    
    pattern:  /evenements
    defaults: { _controller: MilleEtangsRandonneesBundle:Default:events }

articles:    
    pattern:  /articles
    defaults: { _controller: MilleEtangsRandonneesBundle:Default:articles }

accomodations:    
    pattern:  /hebergement
    defaults: { _controller: MilleEtangsRandonneesBundle:Default:accomodations }

restaurants:    
    pattern:  /restauration
    defaults: { _controller: MilleEtangsRandonneesBundle:Default:restaurants }

partners:    
    pattern:  /partenaires
    defaults: { _controller: MilleEtangsRandonneesBundle:Default:partners }

advice:    
    pattern:  /conseils
    defaults: { _controller: MilleEtangsRandonneesBundle:Default:advice }

contact:    
    pattern:  /contact
    defaults: { _controller: MilleEtangsRandonneesBundle:Default:contact }

sitemap:    
    pattern:  /sitemap
    defaults: { _controller: MilleEtangsRandonneesBundle:Default:sitemap }

sitemap_xml:    
    pattern:  /sitemap.{_format}
    defaults: { _controller: MilleEtangsRandonneesBundle:Default:sitemap }
    requirements:
      _format:  html|xml

rss:    
    pattern:  /rss.xml
    defaults: { _controller: MilleEtangsRandonneesBundle:Default:rss }