# Security
login:
    pattern: /login
    defaults: { _controller: MilleEtangsRandonneesBundle:Security:login }

login_check:
    pattern: /login_check
    defaults: { _controller: MilleEtangsRandonneesBundle:Security:loginCheck }

logout:
    pattern: /logout
    defaults: { _controller: MilleEtangsRandonneesBundle:Security:logout }

admin_menu:
    pattern: /menu
    defaults: { _controller: MilleEtangsRandonneesBundle:Security:menu }

upload_image:
    pattern: /upload_image
    defaults: { _controller: MilleEtangsRandonneesBundle:Security:uploadImage}
