# Security
login:
    pattern: /login
    defaults: { _controller: MilleEtangsRandonneesBundle:Security:login }

login_check:
    pattern: /login_check
    defaults: { _controller: MilleEtangsRandonneesBundle:Security:loginCheck }

logout:
    pattern: /logout
    defaults: { _controller: MilleEtangsRandonneesBundle:Security:logout }

admin_menu:
    pattern: /menu
    defaults: { _controller: MilleEtangsRandonneesBundle:Security:menu }

create_itineary:
    pattern: /itineary/create
    defaults: { _controller: MilleEtangsRandonneesBundle:Security:createItineary }

update_itineary:
    pattern: /itineary/update/{id}
    defaults: { _controller: MilleEtangsRandonneesBundle:Security:updateItineary }

create_article:
    pattern: /article/create
    defaults: { _controller: MilleEtangsRandonneesBundle:Security:createArticle }

update_article:
    pattern: /article/update/{id}
    defaults: { _controller: MilleEtangsRandonneesBundle:Security:updateArticle }

upload_image:
    pattern: /upload_image
    defaults: { _controller: MilleEtangsRandonneesBundle:Security:uploadImage}
