language: php
php:
    - 5.6
    # - 7

sudo: false

services:
    - mongodb
    - redis-server

before_install:    
    - phpenv config-add phpconfig.ini
    - chmod +x bin/install.sh
    - npm install -g bower
    - npm install -g less
    - npm install -g uglify-js
    - npm install -g uglifycss

install:
    - cp app/config/parameters.yml.dist app/config/parameters.yml
    - composer install --dev --prefer-source
    - bin/install.sh
    - bower install

script:
    - php app/console doctrine:mongodb:fixtures:load --env=test
    - php app/console cache:clear
    - bin/phpcs -v --standard=PSR2 --extensions=php src/
    - app/console twig:lint @MilleEtangsRandonneesBundle
    - phpunit --configuration app/phpunit.xml
    - php bin/security-checker security:check composer.lock

notifications:
    email: "tuaillon.mathieu@gmail.com"
