language: php
php:
    - "5.5"
    # - "5.4"
    # - "5.3"

services:
    - mongodb
    - redis-server

before_install:    
    - phpenv config-add phpconfig.ini
    - chmod +x bin/install.sh
    - npm install less
    - npm install uglify-js
    - npm install uglifycss

install:
    - cp app/config/parameters.yml.dist app/config/parameters.yml
    - composer install --prefer-source
    - bin/install.sh

script:
    - php app/console doctrine:mongodb:fixtures:load --env=test
    - bin/phpcs -v --standard=PSR2 --extensions=php src/
    - phpunit --configuration app/phpunit.xml

notifications:
    email: "tuaillon.mathieu@gmail.com"