imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: bundles/sonata.yml }
    - { resource: bundles/disqus.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  %locale%
    trusted_proxies: ['127.0.0.1']
    session:
        name:        randos

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
        ga_tracking: UA-50781575-1

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: true
    filters:
        less:
            node: /usr/bin/nodejs
            node_paths: [/usr/local/lib/node_modules]
            apply_to: "\.less$"
        cssrewrite: ~
        uglifyjs2:
            bin: /usr/local/bin/uglifyjs
        uglifycss:
            bin: /usr/local/bin/uglifycss

# Doctrine
doctrine_mongodb:
  connections:
    default:
      server: %mongodb_server%
      options: {}
  default_database: mille_etangs_%kernel.environment%
  document_managers:
    default:
      mappings:
        MilleEtangsRandonneesBundle: ~
      metadata_cache_driver: array

sonata_admin:
    title:      Mille étangs
    templates:
        layout:  MilleEtangsRandonneesBundle:Security:sonata_admin_base_layout.html.twig

knp_menu:
    twig:
        template: knp_menu.html.twig
    templating: false
    default_renderer: twig

jms_di_extra:
    locations:
        all_bundles: false
        bundles: [MilleEtangsBundle]
        directories: ["%kernel.root_dir%/../src"]

stof_doctrine_extensions:
    mongodb:
        default:
            sluggable: true

liip_imagine:
    resolvers:
       default:
          web_path: ~
    filter_sets:
        cache: ~
        my_thumb:
            quality: 85
            filters:
                thumbnail: { size: [120, 90], mode: outbound }
