imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: admin.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  %locale%
    trusted_proxies: ['127.0.0.1']
    session:         ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
        ga_tracking: UA-50781575-1

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    filters:
        less:
            node: /usr/bin/nodejs
            node_paths: [/usr/local/lib/node_modules]
            apply_to: "\.less$"
        cssrewrite: ~
        uglifyjs2:
            bin: /usr/local/bin/uglifyjs
        uglifycss:
            bin: /usr/local/bin/uglifycss

doctrine_mongodb:
  connections:
    default:
      server: %mongodb_server%
      options: {}
  default_database: mille_etangs_%kernel.environment%
  document_managers:
    default:
      mappings:
        MilleEtangsRandonneesBundle: ~
      metadata_cache_driver: array

sonata_admin:
    title:      Mille étangs    

services:
    sonata.admin.article:
        class: MilleEtangs\RandonneesBundle\Admin\ArticleAdmin
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, group: "Contenu", label: "Article" }
        arguments:
            - ~
            - MilleEtangs\RandonneesBundle\Document\Article
            - ~
    sonata.admin.itineary:
        class: MilleEtangs\RandonneesBundle\Admin\ItinearyAdmin
        tags:
            - { name: sonata.admin, manager_type: doctrine_mongodb, group: "Contenu", label: "Itinéraire" }
        arguments:
            - ~
            - MilleEtangs\RandonneesBundle\Document\Itineary
            - ~