# jms_security_extra:
#     secure_all_services: false
#     expressions: true

security:
    encoders:
        MilleEtangs\RandonneesBundle\Document\User: 
            algorithm:        sha512
            encode-as-base64: true
            iterations:       5

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        document_members:
            mongodb: {class: "MilleEtangs\RandonneesBundle\Document\User", property: "username"}

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/admin/login$
            security: false

        secured_area:
            pattern:    ^/admin/
            form_login:
                check_path: /admin/login_check
                login_path: /admin/login
                always_use_default_target_path: false
                default_target_path:            /admin/dashboard
                #use_referer:                    false
            logout:
                path:   /admin/logout
                target: /

        frontend:
            pattern: ^/
            anonymous: true

    access_control:
